### ISSUE TITLE
Problemas na compilação

### ISSUE THREAD

**Issue by ViniciosLugli** [WesleiRamos/Godot-Rich-Presence#4]
Tentei compilar pelo arquivo SConstruct usando:
`python SConstruct platform=plataforma arch=64`
e tive como retorno:
```
Traceback (most recent call last):
  File "SConstruct", line 5, in <module>
    platform = ARGUMENTS.get("platform", ARGUMENTS.get("p", "windows"))
NameError: name 'ARGUMENTS' is not defined
```
Tentei substituir os argumentos mas só me gerava mais problemas kkkkkkk
Como proceder?

**Comment by WesleiRamos** [comment]
Você tem que baixar o Scons (https://scons.org) e depois executar o comando `scons platform=(sistema operacional) arch=64`, aqui nesse link [compilando no windows](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_windows.html#compiling-for-windows) você pode ver as ferramentas que são necessárias pra compilar, e aqui [gdnative-cpp-example](https://docs.godotengine.org/en/latest/tutorials/plugins/gdnative/gdnative-cpp-example.html) tem um exemplo com um passo a passo de como utilizar o gdnative.

**Comment by ViniciosLugli** [comment]
Depois de lutar muito contra o scons, consegui usar ele mas está dando que "gdnative_api_struct.gen.h" não existe dentro do godot-cpp:
```
λ scons platform=windows arch=64
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cl /Fosrc\gdlibrary.obj /c src\gdlibrary.cpp /TP /nologo -EHsc -D_DEBUG -MDd "/IC:\Users\vinic\Documents\codigos\godot\Zul Space\godot-cpp\godot_headers" "/IC:\Users\vinic\Documents\codigos\godot\Zul Space\discord-rpc\include" "/IC:\Users\vinic\Documents\codigos\godot\Zul Space\discord-rpc\src" "/IC:\Users\vinic\Documents\codigos\godot\Zul Space\godot-cpp\include" "/IC:\Users\vinic\Documents\codigos\godot\Zul Space\godot-cpp\include\gen" "/IC:\Users\vinic\Documents\codigos\godot\Zul Space\godot-cpp\include\core"
gdlibrary.cpp
C:\Users\vinic\Documents\codigos\godot\Zul Space\godot-cpp\include\core\Godot.hpp(7): fatal error C1083: Não é possível abrir arquivo incluir: 'gdnative_api_struct.gen.h': No such file or directory
scons: *** [src\gdlibrary.obj] Error 2
scons: building terminated because of errors.
```

**Comment by WesleiRamos** [comment]
Executou os comandos igual ao exemplo [gdnative-cpp-example](https://docs.godotengine.org/en/latest/tutorials/plugins/gdnative/gdnative-cpp-example.html#gdnative-c-example)?

**Comment by ViniciosLugli** [comment]
bom ao meu ver sim, eu fiz varias formas pq me confundi muito. Primeiro eu segui o README:
```
godot-cpp
discord-rpc
Godot-Rich-Presence
├── example/
└── src/
```
clonei os três repositos, e usei o scons na pasta `Godot-Rich-Presence`. e deu o problema que mandei logo acima, dps eu seguindo o esquema de exemplo, clonei o `godot-cpp` dentro do `Godot-Rich-Presence` e dei build. Testei e o mesmo problema. Depois apaguei o `godot-cpp` que coloquei antes e de build na que estava na raiz junto com o `discord-rpc`, e deu esse erro quando dei build no `Godot-Rich-Presence`:
```
C:\Users\vinic\Documents\codigos\godot\Zul Space\Godot-Rich-Presence\src\richpresence.h(6): note: consulte a declaração de 'godot::RichPresence'
src\gdlibrary.cpp(14): note: consulte a referência à instanciação 'void godot::register_class<godot::RichPresence>(void)' do modelo que está sendo compilada
C:\Users\vinic\Documents\codigos\godot\Zul Space\godot-cpp\include\core\Godot.hpp(120): error C3861: '___get_base_type_name': identificador não encontrado
scons: *** [src\gdlibrary.obj] Error 2
scons: building terminated because of errors.
```
não sei oque estou fazendo de errado ;-;

**Comment by WesleiRamos** [comment]
Eu não lembro bem exatamente como compila o projeto porque já fazem quase 2 anos que eu escrevi, mas acredito que foi assim:

1. Baixei o godot-cpp e o discord-rpc
2. Gerei o api.json e gerei os arquivos pra compilar [updating-the-apijson-file](https://github.com/godotengine/godot-cpp#updating-the-apijson-file)
3. Depois de gerado eu compilei o godot-cpp
4. Depois compilei o discord-rpc
5. Compilei meu código

Não bem exatamente nessa ordem, mas quase isso.

**Comment by ViniciosLugli** [comment]
Compilei todos certinho,  so que o Godot-Rich-Presence ta dando problema, suponho que seja por causa de alguma atualização, tentei mas não consegui corrigir:
```
\godot-cpp\include\core\Godot.hpp(120): error C2039: ' ___get_base_type_name': não é um membro de 'godot::RichPresence'
\Godot-Rich-Presence\src\richpresence.h(6): note: consulte a declaração de 'godot::RichPresence'
src\gdlibrary.cpp(14): note: consulte a referência à instanciação 'void godot::register_class<godot::RichPresence>(void)' do modelo que está sendo compilada
\godot-cpp\include\core\Godot.hpp(120): error C3861: '___get_base_type_name': identificador não encontrado
```
Fiz alguns teste e parece que vem dessa linha do código gdlibrary.cpp:
```
extern "C" void GDN_EXPORT godot_nativescript_init(void *handle) {
    godot::Godot::nativescript_init(handle);

    godot::register_class<godot::RichPresence>();
}
```
Espero que consiga me ajudar 😔

**Comment by WesleiRamos** [comment]
Tenta trocar o "Reference" por Node ou Sprite [nesse arquivo](https://github.com/WesleiRamos/Godot-Rich-Presence/blob/309cde44db5e0a64b119ca3a568396f0d05a130a/src/richpresence.h).

**Comment by ViniciosLugli** [comment]
Fiquei mexendo e entendi mais ou menos como era, e dentro das classes não há esse  `___get_base_type_name`, não entendo aaaaaaaaaaaaaaaaa. vou tentar baixar versões anteriores do godot-cpp e ver se n é essa que compilei...
