### ISSUE TITLE
Please release built versions of this addon.

### ISSUE THREAD

**Issue by sairam4123** [WesleiRamos/Godot-Rich-Presence#5]
Hello, Would you like to make a CI/CD that builds for MacOSX, Linux, and Windows?

**Comment by coelhucas** [comment]
I can add CI and CD builds using AppVeyor and Travis if @WesleiRamos add me as a collaborator.
Or you can use [this](https://github.com/coelhucas/godot-steam-module) repo as a reference (`.travis.yml` and `appveyor.yml` files) to setup a CI/CD for this from your own fork.

**Comment by sairam4123** [comment]
Forked it, now adding the travis.yml

**Comment by sairam4123** [comment]
Can you do that for me?
I've forked it.

**Comment by coelhucas** [comment]
Hey, I'm sorry. I just noticed that this discord API was deprecated. I'd suggest you to use the [Game SDK](https://discord.com/developers/docs/game-sdk/sdk-starter-guide) instead. There's already an wrap made to work in Godot [here](https://github.com/Drachenfrucht1/godotcord).

**Comment by sairam4123** [comment]
I'm closing this issue.
